// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Vivero.Models
{
    public partial class Plantas
    {
        public Plantas()
        {
            Visitantes = new HashSet<Visitantes>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Valor { get; set; }
        public string Imagen { get; set; }
        [NotMapped]
        public IFormFile ImagenFile { get; set; }
        public int? Jardineros { get; set; }

        public virtual Jardineros JardinerosNavigation { get; set; }
        public virtual ICollection<Visitantes> Visitantes { get; set; }
    }
}